# Generated by Django 3.2.4 on 2022-08-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
