# Generated by Django 3.2.4 on 2021-07-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorcourse',
            name='recent_semester',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
