# Generated by Django 3.2.4 on 2021-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_professorcourse_recent_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='num_students',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
