# Generated by Django 3.2.4 on 2022-08-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_recent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='recent',
            new_name='is_recent',
        ),
    ]
