# Generated by Django 3.2.4 on 2022-11-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_recent_course_is_recent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
            ],
            options={
                'db_table': 'home_professor_alias',
            },
        ),
    ]
