# Generated by Django 3.2.4 on 2021-07-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_grade_num_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.professor'),
        ),
        migrations.AlterField(
            model_name='professorcourse',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor'),
        ),
    ]
