# Generated by Django 3.2.4 on 2023-01-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_professorcourse_dups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
