# Generated by Django 3.2.4 on 2023-03-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_professoralias_alias'),
        ('home', '0007_course_geneds'),
    ]

    operations = [
    ]
