# Generated by Django 3.2.4 on 2023-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20230304_2012'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='professorcourse',
            name='home_profes_recent__7fe73e_idx',
        ),
        migrations.RenameField(
            model_name='professorcourse',
            old_name='recent_semester',
            new_name='semester_taught',
        ),
        migrations.AddIndex(
            model_name='professorcourse',
            index=models.Index(fields=['semester_taught'], name='home_profes_semeste_84f59f_idx'),
        ),
    ]
