# Generated by Django 3.2.5 on 2021-08-11 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, error_messages={'unique': 'A user with this email already exists.'}, help_text='Once an email is set, it cannot be changed. <span id="email_hint_text" style="display: none;"><br /><br /> Planetterp will only send you emails when a review of yours is approved, rejected, or unverified. You can opt out of this in your account settings at any time. <br /><br /> Your email and any other personal data on our site is kept confidential and isn\'t shared with anyone else. If you have any questions about how Planetterp handles your data, please email <a href="mailto:admin@planetterp.com">admin@planetterp.com</a></span>', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
