# Generated by Django 3.2.4 on 2023-05-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_granted_for',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cross_listed_with',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='formerly',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='restrictions',
            field=models.TextField(null=True),
        ),
    ]
