# Generated by Django 3.2.4 on 2021-08-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210812_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_changed',
            field=models.BooleanField(default=False),
        ),
    ]
