# Generated by Django 3.2.5 on 2021-08-12 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_changed',
        ),
    ]
