# Generated by Django 3.2.5 on 2021-08-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='home_audit_log',
        ),
        migrations.CreateModel(
            name='ProfessorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
            options={
                'db_table': 'home_professor_section',
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='professors'
        ),
        migrations.AddField(
            model_name='section',
            name='professors',
            field=models.ManyToManyField(through='home.ProfessorSection', to='home.Professor'),
        ),

    ]
