# Generated by Django 3.2.5 on 2021-08-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210812_2308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discussionreply',
            table='home_discussion_reply',
        ),
        migrations.AlterModelTable(
            name='fall2020search',
            table='home_fall_2020_search',
        ),
        migrations.AlterModelTable(
            name='groupmegroup',
            table='home_groupme_group',
        ),
        migrations.AlterModelTable(
            name='groupmeuser',
            table='home_groupme_user',
        ),
        migrations.AlterModelTable(
            name='professorcourse',
            table='home_professor_course',
        ),
        migrations.AlterModelTable(
            name='resetcode',
            table='home_reset_code',
        ),
        migrations.AlterModelTable(
            name='sectionmeeting',
            table='home_section_meeting',
        ),
        migrations.AlterModelTable(
            name='userschedule',
            table='home_user_schedule',
        ),
    ]
