# Generated by Django 3.2.4 on 2021-08-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210812_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorsection',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.professor'),
        ),
    ]
