# Generated by Django 3.2.5 on 2021-08-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_professorsection_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschedule',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.section'),
        ),
    ]
