# Generated by Django 3.2.5 on 2021-08-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_professor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
    ]
