# Generated by Django 3.2.5 on 2021-12-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_professor_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fall2020Search',
        ),
    ]
