# Generated by Django 3.2.5 on 2021-12-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_fall2020search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionreply',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='user',
        ),
        migrations.AlterField(
            model_name='grade',
            name='historical',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='DiscussionReply',
        ),
    ]
