# Generated by Django 3.2.4 on 2021-12-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20211227_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='historical',
            field=models.BooleanField(),
        ),
    ]
