# Generated by Django 3.2.4 on 2021-12-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_grade_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='historical',
            field=models.BooleanField(default=False),
        ),
    ]
