# Generated by Django 3.2.4 on 2021-12-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_grade_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
