# Generated by Django 3.2.4 on 2022-01-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_professor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='historical',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='historical',
        ),
    ]
