# Generated by Django 3.2.4 on 2022-01-07 17:35

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220107_0251'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', home.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='from_ourumd',
            field=models.BooleanField(default=False),
        ),
    ]
