# Generated by Django 3.2.4 on 2022-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='image_file_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
