# Generated by Django 3.2.4 on 2022-01-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220107_1735'),
        ('home', '0036_rename_website_url_organization_url'),
    ]

    operations = [
    ]
