# Generated by Django 3.2.4 on 2022-01-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_merge_20220108_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
