# Generated by Django 3.2.4 on 2022-01-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_delete_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
