# Generated by Django 3.2.4 on 2022-01-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A Plus'), ('A', 'A'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B', 'B'), ('B-', 'B Minus'), ('C+', 'C Plus'), ('C', 'C'), ('C-', 'C Minus'), ('D+', 'D Plus'), ('D', 'D'), ('D-', 'D Minus'), ('F', 'F'), ('P', 'P'), ('W', 'W'), ('XF', 'Xf')], max_length=2, null=True),
        ),
    ]
