# Generated by Django 3.2.4 on 2022-01-16 02:34

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20220115_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists. If you forgot your <br /> password, please <a href="" data-toggle="modal" data-target="#password-reset-modal" style="color: red;"> <strong>reset your password</strong></a> or login on the left.'}, help_text='Once an email is set, it cannot be changed. <span id="email_hint_text" style="display: none;"><br /><br /> PlantTerp will only send you emails when a review of yours is approved, rejected, or unverified. You can opt out of this in your account settings at any time. <br /><br /> Your email and any other personal data on our site is kept confidential and isn\'t shared with any other entity. If you have any questions about how PlantTerp handles your data, please email <a href="mailto:admin@planetterp.com">admin@planetterp.com</a></span>', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'You must enter a username', 'unique': 'A user with that username already exists.'}, help_text='Once a username is set, it cannot be changed.', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MaxLengthValidator(21, 'Username must be less than 20 characters'), django.core.validators.MinLengthValidator(2, 'Username must be at least 2 characters')]),
        ),
    ]
