# Generated by Django 3.2.4 on 2022-01-16 02:50

from django.db import migrations

def add_site(apps, _schema_editor):
    Site = apps.get_model("sites", "Site")
    # add actual planetterp site. Will have a pk of 2 since sites adds an
    # example site at id 1
    Site.objects.create(domain="planetterp.com", name="planetterp")

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20220116_0234'),
        ('sites', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_site),
    ]
