# Generated by Django 3.2.4 on 2022-01-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20220118_2351'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='home_course_departm_4b085e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_number'], name='home_course_course__b31247_idx'),
        ),
    ]
