# Generated by Django 3.2.4 on 2022-01-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20220119_0251'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_name',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
