# Generated by Django 3.2.4 on 2022-01-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20220119_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='type',
            field=models.CharField(choices=[('professor', 'Professor'), ('TA', 'TA'), ("[('professor', 'professor'), ('TA', 'TA')]", 'Choices Lower')], max_length=50),
        ),
    ]
