# Generated by Django 3.2.4 on 2022-01-21 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_professor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='type',
            field=models.CharField(choices=[('professor', 'Professor'), ('TA', 'TA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists. If you forgot your <br /> password, please <a href="" data-toggle="modal" data-target="#password-reset-modal" style="color: red;"> <strong>reset your password</strong></a> or login on the left.'}, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
