# Generated by Django 3.2.4 on 2022-01-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_professor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='type',
            field=models.CharField(choices=[('professor', 'Professor'), ('TA', 'TA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('P', 'P'), ('W', 'W'), ('XF', 'XF')], max_length=2, null=True),
        ),
    ]
