# Generated by Django 3.2.4 on 2022-01-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20220121_0505'),
        ('home', '0055_auto_20220121_0654'),
    ]

    operations = [
    ]
