# Generated by Django 3.2.4 on 2022-01-21 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'You must enter a username', 'unique': 'A user with that username already exists.'}, max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\d]+$', 'Username can only contain alphanumeric characters and underscores'), django.core.validators.MaxLengthValidator(22, 'Username must be less than 20 characters'), django.core.validators.MinLengthValidator(2, 'Username must be at least 2 characters')]),
        ),
    ]
