# Generated by Django 3.2.4 on 2022-01-21 20:18

from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=home.models.SemesterField(max_length=6),
        ),
        migrations.AlterField(
            model_name='professorcourse',
            name='recent_semester',
            field=home.models.SemesterField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=home.models.SemesterField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='semester',
            field=home.models.SemesterField(max_length=6),
        ),
    ]
