# Generated by Django 3.2.4 on 2022-01-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_user_username'),
        ('home', '0059_auto_20220121_2018'),
    ]

    operations = [
    ]
