# Generated by Django 3.2.4 on 2022-07-24 01:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20220123_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'default_manager_name': 'unfiltered'},
        ),
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='professorcourse',
            index=models.Index(fields=['recent_semester'], name='home_profes_recent__7fe73e_idx'),
        ),
    ]
